#ifndef HAL_CFG_H
#define HAL_CFG_H

#define HAL_CFG_HOST_I2C_MAX_DEVICES       8U
#define HAL_CFG_HOST_I2C_MAX_TRANSFER    512U
#define HAL_CFG_HOST_NET_MAX_HOST_LENGTH 127U
#define HAL_CFG_HOST_NET_MAX_PACKET      512U
#define HAL_CFG_HOST_NET_MAX_CAPTURES     16U
#define HAL_CFG_HOST_NET_RX_QUEUE_DEPTH    8U

#endif
