#ifndef FUNC_CFG_H
#define FUNC_CFG_H

#define FUNC_CFG_MAX_SENSORS             4U
#define FUNC_CFG_MAX_SUBSCRIPTIONS       12U
#define FUNC_CFG_MAX_FILTERS_PER_SENSOR  4U
#define FUNC_CFG_FILTER_MA_MAX_WINDOW    16U
#define FUNC_CFG_FILTER_MEDIAN_MAX_WINDOW 9U
#define FUNC_CFG_TEMP_ERROR_THRESHOLD     3U
#define FUNC_CFG_GUI_QUEUE_CAPACITY       8U
#define FUNC_CFG_MQTT_QUEUE_CAPACITY     16U
#define FUNC_CFG_BIZ_QUEUE_CAPACITY      16U

#endif
