#ifndef PROTO_CFG_H
#define PROTO_CFG_H

#define PROTO_CFG_I2C_MAX_REGISTER_BYTES 4U
#define PROTO_CFG_I2C_MAX_DATA          512U

#define PROTO_CFG_MQTT_TX_QUEUE_CAPACITY 8U

#ifndef PROTO_CFG_MQTT_MAX_PACKET
#define PROTO_CFG_MQTT_MAX_PACKET 512U
#endif

#ifndef PROTO_CFG_MQTT_HOST_CAPACITY
#define PROTO_CFG_MQTT_HOST_CAPACITY 128U
#endif

#ifndef PROTO_CFG_MQTT_CLIENT_ID_CAPACITY
#define PROTO_CFG_MQTT_CLIENT_ID_CAPACITY 64U
#endif

#define PROTO_CFG_MQTT_POLL_BUDGET_MS      2U

#endif
