#ifndef PROTO_CFG_H
#define PROTO_CFG_H

#define PROTO_CFG_I2C_MAX_REGISTER_BYTES 4U
#define PROTO_CFG_I2C_MAX_DATA          512U

#define PROTO_CFG_MQTT_TX_QUEUE_CAPACITY 8U
#define PROTO_CFG_MQTT_MAX_PACKET        512U
#define PROTO_CFG_MQTT_POLL_BUDGET_MS      2U

#endif
